# Form implementation generated from reading ui file '/Users/tuakpina/Projects/PythonProjects/PersonalProjects/YT-Downloader/SettingsWindow/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label = QtWidgets.QLabel(parent=self.tab_7)
        self.label.setGeometry(QtCore.QRect(130, 10, 151, 16))
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(parent=self.tab_7)
        self.okButton.setGeometry(QtCore.QRect(310, 180, 100, 32))
        self.okButton.setObjectName("okButton")
        self.qualityBox = QtWidgets.QComboBox(parent=self.tab_7)
        self.qualityBox.setGeometry(QtCore.QRect(130, 100, 103, 32))
        self.qualityBox.setObjectName("qualityBox")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.qualityBox.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=self.tab_7)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.tab_7)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 111, 16))
        self.label_2.setObjectName("label_2")
        self.formatBox = QtWidgets.QComboBox(parent=self.tab_7)
        self.formatBox.setGeometry(QtCore.QRect(130, 70, 103, 32))
        self.formatBox.setObjectName("formatBox")
        self.formatBox.addItem("")
        self.formatBox.addItem("")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget.addTab(self.tab_8, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.okButton.setText(_translate("Form", "OK"))
        self.qualityBox.setItemText(0, _translate("Form", "The Best"))
        self.qualityBox.setItemText(1, _translate("Form", "2160p"))
        self.qualityBox.setItemText(2, _translate("Form", "1440p"))
        self.qualityBox.setItemText(3, _translate("Form", "1080p"))
        self.qualityBox.setItemText(4, _translate("Form", "720p"))
        self.qualityBox.setItemText(5, _translate("Form", "480p"))
        self.qualityBox.setItemText(6, _translate("Form", "240p"))
        self.qualityBox.setItemText(7, _translate("Form", "144p"))
        self.label_3.setText(_translate("Form", "Video Quality"))
        self.label_2.setText(_translate("Form", "Video Format"))
        self.formatBox.setItemText(0, _translate("Form", "mp4"))
        self.formatBox.setItemText(1, _translate("Form", "mkv"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Form", "Video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("Form", "Audio"))
